class BanditUsageError(Exception):
    """Raised when bandit functions are called out of order"""

    pass
